export enum ConfigKeys {
  SERVER_PORT = 'SERVER_PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  NODE_ENV = 'NODE_ENV',

  SWAGGER_ROUTE = 'SWAGGER_ROUTE',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_RESAVE = 'SESSION_RESAVE',

  SESSION_SAVE_UNINIT = 'SESSION_SAVE_UNINIT',
  COOKIE_SECURE = 'COOKIE_SECURE',
  COOKIE_HTTP_ONLY = 'COOKIE_HTTP_ONLY',
  COOKIE_MAX_AGE = 'COOKIE_MAX_AGE',

  USER_PASS_SALT = 'USER_PASS_SALT',
}
