export enum DBConfigKeys {
  DB_DIALECT = 'DB_DIALECT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_AUTO_LOAD_MODELS = 'DB_AUTO_LOAD_MODELS',
  DB_SYNCHRONIZE_MODELS = 'DB_SYNCHRONIZE_MODELS',
}
